version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/host"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
