name: ci
on: push
jobs:
  check-host:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: host
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - run: make check
  check-extension:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: extension
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm ci
      - run: make check
