name: ci
on: push
jobs:
  check-host:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: host
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: host/go.mod
      - run: go mod download && go mod verify
      - run: make check
  check-extension:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: extension
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: extension/package.json
      - run: npm ci --no-fund
      - run: make check
